#!/usr/bin/env python3
"""Validate final repo openwiki usability and lifecycle wiring."""

from __future__ import annotations

import os
import sys
from pathlib import Path


ROOT = Path(os.environ.get("OPENWIKI_ROOT", Path(__file__).resolve().parents[1]))

REQUIRED_FILES = [
    "README.md",
    # The declared openwiki_entry. Existence only -- it is generated by the wiki
    # pipeline on every run, so pinning its content would freeze a generated file.
    "openwiki/quickstart.md",
    "openwiki/nonofficial/README.md",
    "openwiki/nonofficial/usage.md",
    "openwiki/nonofficial/asset-lifecycle-map.md",
    "openwiki/nonofficial/stateful-workflow.md",
    "openwiki/nonofficial/code-call-lifecycle.md",
    "openwiki/nonofficial/production-bottlenecks.md",
    "openwiki/nonofficial/autoresearch-composer-lifecycle.md",
    "openwiki/nonofficial/structured-lifecycle-data.md",
    "openwiki/nonofficial/prompt-trace-assets.md",
    "openwiki/nonofficial/wiki-graph-sync-architecture.md",
    "openwiki/nonofficial/schema-standards.md",
    "openwiki/nonofficial/openwiki.yaml",
]

REQUIRED_LITERALS = {
    "README.md": [
        "Usage Entry",
        "python3 scripts/git_gate.py",
        "openwiki/quickstart.md",
    ],
    "openwiki/nonofficial/README.md": [
        "Usage Entry",
        "Asset Lifecycle Map",
        "stateful-workflow.md",
        "production-bottlenecks.md",
        "autoresearch-composer-lifecycle.md",
        "wiki-graph-sync-architecture.md",
        "schema-standards.md",
        "prompt-trace-assets.md",
    ],
    "openwiki/nonofficial/asset-lifecycle-map.md": [
        "Compile Phase",
        "Git Commit/Push Hook",
        "CI/CD Regression Gate",
        "Production Execution",
        "Weekly Ablation Audit & Retirement",
        "scripts/git_gate.py",
        "scripts/llm_judge.py",
    ],
    "openwiki/nonofficial/stateful-workflow.md": [
        "S1 Match Repo Shape",
        "S3 Generate Skill Asset",
        "S5 Validate Static Defenses",
        "conditional_edge.S7.openwiki_fail",
        "Matching, generation, and validation are separate",
    ],
    "openwiki/nonofficial/code-call-lifecycle.md": [
        ".githooks/pre-push",
        "scripts/git_gate.py",
        "scripts/check_openwiki.py",
        ".github/workflows/skill_ci.yml",
        "scripts/check_plan_package_compat.py",
        ".github/workflows/autoresearch_eval.yml",
        ".github/workflows/wiki_graph_sync.yml",
        "scripts/sync_wiki_to_graph.py",
        "scripts/check_wiki_graph_sync.py",
        "scripts/validate_molecular_commit_lineage.py",
        "data/commit_lineage/gcr_molecular_commits.json",
        "gcr_molecular_commits.json: protected_history=157 compensated=157 failed=0 schema=v0.2",
        "Autoresearch-Composer Eval Call Graph",
        "wiki_graph_sync.yml",
        "local_llm_as_judge()",
        "pr_golden_set.json: cases=4 passed=4",
        "delta=1.0 verdict=PASS",
    ],
    "openwiki/nonofficial/autoresearch-composer-lifecycle.md": [
        "Concrete Optimization",
        "Golden Standard Example",
        "Executed Autoresearch-Composer Data",
        "Lifecycle Data Artifacts",
        "Missing Future Hardening",
        "cases=4",
        "passed=4",
        "sample_count=3",
        "case_count=12",
        "delta=1.0",
        "cloud_judge_enabled=false",
    ],
    "openwiki/nonofficial/structured-lifecycle-data.md": [
        "Structured Lifecycle Data",
        "data/lifecycle/skill_optimization_registry.json",
        "autoresearch_composer",
        "autoresearch-pr-golden@2026-07-23",
        "autoresearch-composer-2026-07-23-local",
        "candidate_until_human_admit",
        "failure_trace_sample_count",
    ],
    "openwiki/nonofficial/prompt-trace-assets.md": [
        "Prompt Trace Assets",
        "data/prompt_trace/prompt_trace_dataset.json",
        "data/prompt_trace/golden_prompt_trace_eval.json",
        "scripts/check_prompt_trace_assets.py",
        "fixed_prompt",
        "iteration_auto_prompt",
        "emergent_prompt",
        "judge-loop-chooser",
        "metadata-local prompt traces",
    ],
    "openwiki/nonofficial/wiki-graph-sync-architecture.md": [
        "Event Sourcing",
        "Vector RAG",
        "GraphRAG",
        "LLM Wiki",
        "W5.graph_secrets_missing",
        ".github/workflows/wiki_graph_sync.yml",
    ],
    "openwiki/nonofficial/schema-standards.md": [
        "WikiDocument",
        "WikiEvent",
        "EmbeddingMetadata",
        "LicenseProvenance",
        "Apache-2.0",
    ],
    "openwiki/nonofficial/production-bottlenecks.md": [
        "skill-bettor repo-wiki control plane",
        "local-zero-LLM-regex-canary",
        "root-local-runtime",
        "documentation debt",
    ],
    "openwiki/nonofficial/openwiki.yaml": [
        "openwiki_version: openwiki@0.1.0",
        "openwiki_entry: openwiki/quickstart.md",
        "autoresearch_lifecycle_page: openwiki/nonofficial/autoresearch-composer-lifecycle.md",
        "structured_lifecycle_page: openwiki/nonofficial/structured-lifecycle-data.md",
        "prompt_trace_page: openwiki/nonofficial/prompt-trace-assets.md",
        "prompt_trace_dataset: data/prompt_trace/prompt_trace_dataset.json",
        "prompt_trace_gate: scripts/check_prompt_trace_assets.py",
        "wiki_graph_sync_page: openwiki/nonofficial/wiki-graph-sync-architecture.md",
        "schema_standards_page: openwiki/nonofficial/schema-standards.md",
        "wiki_graph_sync_workflow: .github/workflows/wiki_graph_sync.yml",
        "commit_lineage_ledger: data/commit_lineage/gcr_molecular_commits.json",
        "commit_lineage_verification_run: data/verification_runs/gcr_three_surface_commit_traceability_2026-07-27.json",
        "commit_lineage_validator: scripts/validate_molecular_commit_lineage.py",
        "final_repo_small_loop_policy: forbidden",
    ],
}


def main() -> int:
    failures: list[str] = []
    for relative in REQUIRED_FILES:
        path = ROOT / relative
        if not path.is_file():
            failures.append(f"missing file: {relative}")
            continue
        text = path.read_text(encoding="utf-8")
        for literal in REQUIRED_LITERALS.get(relative, []):
            if literal not in text:
                failures.append(f"{relative} missing literal: {literal}")
    for forbidden in ("small-loop", "packets", "templates/skill-defense-governance"):
        if (ROOT / forbidden).exists():
            failures.append(f"forbidden final repo path exists: {forbidden}")
    if failures:
        print("FAIL: openwiki validation failed", file=sys.stderr)
        print("\n".join(failures), file=sys.stderr)
        return 2
    print("PASS: openwiki usage and lifecycle wiring")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
